use serde::Deserialize;
use serde::Serialize;

#[derive(Default, Serialize, Deserialize, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum TaxonomicRank {
    Regnum,
    Subregnum,
    Superphylum,
    Phylum,
    Subphylum,
    Infraphylum,
    Superclassis,
    Classis,
    Subclassis,
    Infraclassis,
    Superordo,
    Ordo,
    Subordo,
    Infraordo,
    Superfamilia,
    Familia,
    Subfamilia,
    Infrafamilia,
    Supertribus,
    Tribus,
    Subtribus,
    Infratribus,
    Supergenus,
    Genus,
    Subgenus,
    Infragenus,
    #[default]
    Species,
    Subspecies,
    Complex,
}

impl TaxonomicRank {
    pub const ALL: [Self; 29] = [
        Self::Regnum,
        Self::Subregnum,
        Self::Superphylum,
        Self::Phylum,
        Self::Subphylum,
        Self::Infraphylum,
        Self::Superclassis,
        Self::Classis,
        Self::Subclassis,
        Self::Infraclassis,
        Self::Superordo,
        Self::Ordo,
        Self::Subordo,
        Self::Infraordo,
        Self::Superfamilia,
        Self::Familia,
        Self::Subfamilia,
        Self::Infrafamilia,
        Self::Supertribus,
        Self::Tribus,
        Self::Subtribus,
        Self::Infratribus,
        Self::Supergenus,
        Self::Genus,
        Self::Subgenus,
        Self::Infragenus,
        Self::Species,
        Self::Subspecies,
        Self::Complex,
    ];

    pub const fn latin_name(&self) -> &'static str {
        match self {
            Self::Regnum => "regnum",
            Self::Subregnum => "subregnum",
            Self::Superphylum => "superphylum",
            Self::Phylum => "phylum",
            Self::Subphylum => "subphylum",
            Self::Infraphylum => "infraphylum",
            Self::Superclassis => "superclassis",
            Self::Classis => "classis",
            Self::Subclassis => "subclassis",
            Self::Infraclassis => "infraclassis",
            Self::Superordo => "superordo",
            Self::Ordo => "ordo",
            Self::Subordo => "subordo",
            Self::Infraordo => "infraordo",
            Self::Superfamilia => "superfamilia",
            Self::Familia => "familia",
            Self::Subfamilia => "subfamilia",
            Self::Infrafamilia => "infrafamilia",
            Self::Supertribus => "supertribus",
            Self::Tribus => "tribus",
            Self::Subtribus => "subtribus",
            Self::Infratribus => "infratribus",
            Self::Supergenus => "supergenus",
            Self::Genus => "genus",
            Self::Subgenus => "subgenus",
            Self::Infragenus => "infragenus",
            Self::Species => "species",
            Self::Subspecies => "subspecies",
            Self::Complex => "complex",
        }
    }

    pub const fn en_name(&self) -> &'static str {
        match self {
            Self::Regnum => "kingdom",
            Self::Subregnum => "subkingdom",
            Self::Superphylum => "superphylum",
            Self::Phylum => "phylum",
            Self::Subphylum => "subphylum",
            Self::Infraphylum => "infraphylum",
            Self::Superclassis => "superdivision",
            Self::Classis => "division",
            Self::Subclassis => "subdivision",
            Self::Infraclassis => "infraclassis",
            Self::Superordo => "superorder",
            Self::Ordo => "order",
            Self::Subordo => "suborder",
            Self::Infraordo => "infraorder",
            Self::Superfamilia => "superfamily",
            Self::Familia => "family",
            Self::Subfamilia => "subffamily",
            Self::Infrafamilia => "infrafamily",
            Self::Supertribus => "supertribe",
            Self::Tribus => "tribe",
            Self::Subtribus => "subtribe",
            Self::Infratribus => "infratribe",
            Self::Supergenus => "supergenus",
            Self::Genus => "genus",
            Self::Subgenus => "subgenus",
            Self::Infragenus => "infragenus",
            Self::Species => "species",
            Self::Subspecies => "subspecies",
            Self::Complex => "complex",
        }
    }

    pub const fn pl_name(&self) -> &'static str {
        match self {
            Self::Regnum => "królestwo",
            Self::Subregnum => "podkrólestwo",
            Self::Superphylum => "nadtyp",
            Self::Phylum => "typ",
            Self::Subphylum => "podtyp",
            Self::Infraphylum => "infratyp",
            Self::Superclassis => "nadgromada",
            Self::Classis => "gromada",
            Self::Subclassis => "podgromada",
            Self::Infraclassis => "infragromada",
            Self::Superordo => "nadrząd",
            Self::Ordo => "rząd",
            Self::Subordo => "podrząd",
            Self::Infraordo => "infrarząd",
            Self::Superfamilia => "nadrodzina",
            Self::Familia => "rodzina",
            Self::Subfamilia => "podrodzina",
            Self::Supertribus => "nadplemię",
            Self::Tribus => "plemię",
            Self::Subtribus => "podplemię",
            Self::Supergenus => "nadrodzaj",
            Self::Genus => "rodzaj",
            Self::Subgenus => "podrodzaj",
            Self::Species => "gatunek",
            Self::Subspecies => "podgatunek",
            Self::Complex => "kompleks",
            Self::Infrafamilia | Self::Infratribus | Self::Infragenus => self.latin_name(),
        }
    }
}
